### ISSUE TITLE
bug in inversion\dlg.py", line 127, in _dlg_attack     x_grad = paddle.grad(loss_grad, dummy_x, retain_graph=True, allow_unused=False)

### ISSUE THREAD

**Issue by 876186439** [PaddlePaddle/PaddleSleeve#3]
RuntimeError: (PermissionDenied) Reference count must be 0 when ready var generated_tensor_70@GRAD is set
  [Hint: Expected ready_var.cur_ref_cnt == 0, but received ready_var.cur_ref_cnt:1 != 0:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\partial_grad_engine.cc:492)

**Comment by Yanghello** [comment]
感谢反馈的bug，这个bug将在 #6 中fix
