### ISSUE TITLE
dw_mul[i][i] = 0不能改变dw_mul值

### ISSUE THREAD

**Issue by 876186439** [PaddlePaddle/PaddleSleeve#4]
dig.py中_attack_label：
        for i in range(dw_mul.shape[0]):
            dw_mul[i][i] = 0
            all_le_zero = all(x <= 0 for x in dw_mul[i])
            if all_le_zero:
                return i
实际运行中在这里 dw_mul[i][i] = 0没有将（i，i）的值改变？

**Comment by Yanghello** [comment]
感谢反馈的bug，这个bug将在 #6 中fix
